{
    "props": {
        "pageProps": {
            "host": "https://web.chutcha.net",
            "qs": {"keys": "bGR6S0JaZ1VHbWNSSTR2aWI2VGVDQT09"},
            "keys": "bGR6S0JaZ1VHbWNSSTR2aWI2VGVDQT09",
            "metaValueObj": {
                "title": "기아 스팅어 마이스터 3.3 터보 GT 아크로에디션 - 중고차는 첫차",
                "ogTitle": "기아 스팅어 마이스터 3.3 터보 GT 아크로에디션 - 중고차는 첫차",
                "ogType": "website",
                "ogDescription": "지금 첫차에서 기아 스팅어 마이스터 3.3 터보 GT 아크로에디션 중고차를 만나보세요. 주행거리: 37,427km, 연료: 가솔린, 연식: 2022년 11월",
                "ogImage": "https://imgsc.chutcha.kr/files/car_resist/202503/03/2025030312110117409714618955_ori.jpg?s=1024x768&t=crop",
                "ogUrl": "https://web.chutcha.net/bmc/detail/bGR6S0JaZ1VHbWNSSTR2aWI2VGVDQT09",
                "imageSrc": "https://imgsc.chutcha.kr/files/car_resist/202503/03/2025030312110117409714618955_ori.jpg?s=1024x768&t=crop",
            },
            "ldJson": {
                "@context": "https://schema.org/",
                "@type": ["Product", "Vehicle"],
                "image": "https://imgsc.chutcha.kr/files/car_resist/202503/03/2025030312110117409714618955_ori.jpg?s=1024x768&t=crop",
                "name": "기아 스팅어 마이스터 3.3 터보 GT 아크로에디션",
                "description": "기아 스팅어 마이스터 3.3 터보 GT 아크로에디션 중고 차량, 37,427km, 가솔린, 2022년 11월 (23년형) 최초 등록",
                "color": "남색",
                "brand": {"@type": "Brand", "name": "기아"},
                "model": "스팅어 마이스터",
                "fuelType": "가솔린",
                "mileageFromOdometer": {"value": "37427", "unitCode": "KTM"},
                "vehicleModelDate": "2023",
                "itemCondition": "https://schema.org/UsedCondition",
                "review": {
                    "@type": "Review",
                    "reviewRating": {
                        "@type": "Rating",
                        "ratingValue": 5,
                        "bestRating": "5.0",
                        "worstRating": "0.0",
                    },
                    "author": {
                        "@type": "Person",
                        "name": "이종호 딜러",
                        "url": "https://www.chutcha.net/share/dealer/dealer_room/47381660daf38c318849daa52f2bfd6c",
                    },
                    "reviewBody": "☆이종호 부장의 이벤트☆\r\n       놓치지 마세요 !!\r\n\r\n2025년 이벤트 ☆\r\n\r\n기대하셔도 좋습니다 ☆\r\n\r\n☆이종호 부장의 소개글 ☆\r\n\r\n12년동안의 영업하면서 \r\n\r\n고객님 한분한분 원하시는 차량을 \r\n\r\n맞춰서 선보인 노하우  기대하셔도 좋습니다!!\r\n\r\n첫차에서는 100% 확인된 차량을 광고 중이며 \r\n\r\n꼼꼼히 심사후 차량을 판매 중 입니다 .\r\n\r\n고객 니즈에 맞춰서 후회 없는 중고차 구매의 힘쓰겠습니다 .  \r\n\r\n◇문의안내 \r\n\r\n24시 상담이 가능하오니 편하게 연락 주시길 바랍니다 .\r\n\r\n통화가 혹시나 어려울때는 문자를 남겨 주시면 빠른 답변 드리겠습니다 .\r\n방문전 연락을 부탁 드립니다 .\r\n\r\n☆고객이 자주하는 질문☆\r\n\r\n1 .할부? 현금? 둘 다 가능한가요?\r\n가능합니다. 은행 중고차할부 프로그램을 통하여 저금리로 적용받으실 수 있습니다.\r\n\r\n2. 비대면 구매 가능한가요?\r\n매장 방문이 힘드시거나 바쁘신 고객님들 \r\n직접 차량상태 확인, 정비 정검 및 보험가입까지 완벽히\r\n안전하게 차량인도를 도와드리겠습니다 \r\n\r\n3.차량 출고 후 결함발견시 사후처리는요?\r\n매입 된 모든 차량은 보험사에 보증보험을 가입하고 출고 합니다. 결함/하자 발생시 가까운 제휴정비소에 입고하여 보증 받으시면 됩니다.\r\n(30일 또는 2,000km 내, 보험사 보증범위 대상)\r\n\r\n4. 타던 차량 처리가능한가요?\r\n가능합니다. 자동차진단 평가사가 정확한 고객님의 차량상태를 확인 후 매입합니다.소유중이신 차량의 단가를 최고가로 매입을 약속 드리겠습니다 \r\n\r\n5. 차구입 시 시간이 얼마나 걸리나요?\r\n현금구입시 약1시간 할부구입시 약 2시간 소요\r\n\r\n◇탁송거래\r\n매장 방문이 힘드시거나 바쁘신 고객님들 \r\n직접 차량상태 확인, 정비 정검 및 보험가입까지 완벽히\r\n안전하게 차량인도를 도와드리겠습니다 \r\n\r\n◇차량매입 , 대차가능\r\n \r\n소유중이신 차량의 단가를 최고가로 매입을 약속 드리겠습니다 \r\n\r\n◇오시는길\r\n→ 주소 : 수원시 권선구",
                },
                "aggregateRating": {
                    "@type": "AggregateRating",
                    "ratingValue": "5.0",
                    "reviewCount": "55",
                },
            },
            "isMobile": False,
            "dehydratedState": {
                "mutations": [],
                "queries": [
                    {
                        "state": {
                            "data": {
                                "is_lease": "0",
                                "lease_type": "0",
                                "is_cpo": "0",
                                "is_callbanner": "0",
                                "is_ew": "0",
                                "car_status": "1001",
                                "banner_info": {
                                    "300": {
                                        "banner_id": "219",
                                        "flag": "300",
                                        "log_show_name": "ccPC_detail",
                                        "img_alt_text": "",
                                        "img": "/files/chutchaApp/popup/202503/1106c10c9bff00ad43775cb4c193f288.png",
                                        "href": "https://web.chutcha.net/board/view/1043?flow_route=pc_cdbanner",
                                        "target": "1002",
                                        "show_position": "0",
                                        "top_title": "",
                                        "bottom_title": "",
                                        "btn_title": "",
                                        "btn_href": "",
                                        "bg_color": "",
                                    },
                                    "301": {
                                        "banner_id": "85",
                                        "flag": "301",
                                        "log_show_name": "wingad_left",
                                        "img_alt_text": "",
                                        "img": "/files/chutchaApp/popup/202407/4ed8a21f4ad2d002f2328fa50c44c4e8.png",
                                        "href": "https://sell.chutcha.net/main/main",
                                        "target": "1002",
                                        "show_position": "1",
                                        "top_title": "",
                                        "bottom_title": "",
                                        "btn_title": "",
                                        "btn_href": "",
                                        "bg_color": "",
                                    },
                                    "302": {
                                        "banner_id": "2",
                                        "flag": "302",
                                        "log_show_name": "smc_pcdetail",
                                        "img_alt_text": "",
                                        "img": "/files/chutchaApp/popup/202308/226f20e71dc90c550457a055ed08b98c.png",
                                        "href": "https://sell.chutcha.net/main/main?flow_route=pcdetail",
                                        "target": "1002",
                                        "show_position": "2",
                                        "top_title": "",
                                        "bottom_title": "",
                                        "btn_title": "",
                                        "btn_href": "",
                                        "bg_color": "",
                                    },
                                },
                                "cpo_banner_info": {},
                                "reg_dealer_info": {
                                    "user_no": "1436889",
                                    "user_name": "이종호",
                                    "dealer_flag": "1",
                                    "phone": "0504-0886-6899",
                                    "vns_no": "0504-0886-6899",
                                    "shop_name": "카마존",
                                    "profile_path": "/files/member_dealer/202404/11/8b435a9c02782f08ebf139962aaa3eb4.jpg",
                                    "complex_type": "1001",
                                    "sido": "경기",
                                    "gugun": "수원시 권선구",
                                    "complex_name": "SKV1모터스",
                                    "shop_addr": "경기 수원시 권선구 평동로79번길 45 (평동, 수원 SK V1 motors)",
                                    "mark_car_big": "",
                                    "mark_car_sm": "",
                                    "action_url": "",
                                    "action_url_title": "",
                                    "avg_marks": "5.0",
                                    "review_cnt": "55",
                                    "call_img": "/images/chutcha/dealer_verify/32/24732/d98929697e35eed19ef419a1dd740ede.jpg",
                                    "hash_key": "47381660daf38c318849daa52f2bfd6c",
                                    "share_short_url": "https://www.chutcha.net/share/dealer/dealer_room/47381660daf38c318849daa52f2bfd6c",
                                    "is_dealer_certify": "1",
                                    "dealer_flag_str": "딜러",
                                },
                                "call_dealer_info": {
                                    "user_no": "1436889",
                                    "user_name": "이종호",
                                    "dealer_flag": "1",
                                    "phone": "0504-0886-6899",
                                    "vns_no": "0504-0886-6899",
                                    "shop_name": "카마존",
                                    "profile_path": "/files/member_dealer/202404/11/8b435a9c02782f08ebf139962aaa3eb4.jpg",
                                    "complex_type": "1001",
                                    "sido": "경기",
                                    "gugun": "수원시 권선구",
                                    "complex_name": "SKV1모터스",
                                    "shop_addr": "경기 수원시 권선구 평동로79번길 45 (평동, 수원 SK V1 motors)",
                                    "mark_car_big": "",
                                    "mark_car_sm": "",
                                    "action_url": "",
                                    "action_url_title": "",
                                    "avg_marks": "5.0",
                                    "review_cnt": "55",
                                    "call_img": "/images/chutcha/dealer_verify/32/24732/d98929697e35eed19ef419a1dd740ede.jpg",
                                    "hash_key": "47381660daf38c318849daa52f2bfd6c",
                                    "share_short_url": "https://www.chutcha.net/share/dealer/dealer_room/47381660daf38c318849daa52f2bfd6c",
                                    "is_dealer_certify": "1",
                                    "dealer_flag_str": "딜러",
                                    "is_callbanner_dealer": "0",
                                },
                                "img_list": [
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110117409714618955.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110217409714626365.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110117409714618951.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110117409714618981.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110117409714618911.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110117409714618977.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110117409714618926.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110217409714624762.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110217409714625680.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110217409714625277.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110217409714627225.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110217409714627304.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714630856.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714631178.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714631899.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714632033.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714632352.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714632679.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714636152.jpg"
                                    },
                                    {
                                        "img_path": "/files/car_resist/202503/03/2025030312110317409714636680.jpg"
                                    },
                                ],
                                "img_list_banner": {
                                    "path": "https://img.chutcha.kr/files/website/chutcha_pc/sub/car_detail/img_appdown_modal_banner.png",
                                    "url_link": "https://sell.chutcha.net",
                                },
                                "safe_info": {
                                    "mileage_safe": {
                                        "mileage": "37427",
                                        "first_reg_year": "2022",
                                        "first_reg_month": "11",
                                        "mile_avg": "16060",
                                        "mile1": "10001",
                                        "mile2": "6001",
                                        "mile3": "-1000",
                                        "mile4": "-4000",
                                    },
                                    "market_safe": {"new_car_price": "0"},
                                    "perform_safe": {
                                        "is_cpo": "0",
                                        "performance_type": "1",
                                        "perform_url": "",
                                        "change_num": "0",
                                        "metal_num": "2",
                                        "corrosion_num": "0",
                                        "uneven_num": "0",
                                        "scratch_num": "0",
                                        "damage_num": "0",
                                        "icon_type": "2",
                                        "fix_img_list": [
                                            {
                                                "parts_name": "조수석 리어 도어",
                                                "parts_desc": "리어 도어는 자동차의 외관을 이루는 부분 중 하나로 유리창이 부착되어 있는 문을 의미합니다.",
                                                "fix_type": "판금",
                                                "fix_img": "https://img.chutcha.kr/images/chutcha/car3d/all_7_1003_full.jpg",
                                            },
                                            {
                                                "parts_name": "조수석 쿼터패널",
                                                "parts_desc": "쿼터패널은 뒤 타이어 상단 부분으로 ‘C’ 필러와 트렁크의 사이드 부분의 외부 패널 입니다.",
                                                "fix_type": "판금",
                                                "fix_img": "https://img.chutcha.kr/images/chutcha/car3d/all_11_1003_full.jpg",
                                            },
                                        ],
                                    },
                                    "carhistory_safe": {
                                        "carAccInfo": {"accident_icon_type": "2"},
                                        "insurance": {
                                            "date": "2024.12.26",
                                            "list": [
                                                {
                                                    "type": "1",
                                                    "price": "7467145",
                                                    "date": "20221127",
                                                    "sort_date": "20221127",
                                                }
                                            ],
                                        },
                                    },
                                },
                                "base_info": {
                                    "fuel_id": "1",
                                    "year_str": "2022년 11월 (23년형)",
                                    "mileage": "37,427km",
                                    "number_plate": "305저5271",
                                    "fuel_name": "가솔린",
                                    "transmission_name": "오토",
                                    "car_type": "중대형",
                                    "displacement": "3,342cc",
                                    "fuel_efficient_grade": "",
                                    "fuel_efficient": "8.8 km/L",
                                    "color": "남색",
                                    "shop_info": "",
                                    "car_location": "경기 수원시 권선구 SKV1모터스",
                                    "car_id": "3134818",
                                    "brand_name": "기아",
                                    "model_name": "스팅어",
                                    "sub_model_name": "스팅어 마이스터",
                                    "f_fuel_name": "가솔린",
                                    "f_cc_name": "2WD",
                                    "grade_name": "3.3 터보 GT 아크로에디션",
                                    "sub_grade_name": "",
                                    "make_year": "2023",
                                    "first_reg_year": "2022",
                                    "first_reg_month": "11",
                                    "plain_price": "3450",
                                    "plain_mileage": "37427",
                                    "car_share_url": "https://www.chutcha.net/share/car/detail/bGR6S0JaZ1VHbWNSSTR2aWI2VGVDQT09",
                                    "check_real_status": "1",
                                    "check_real_date": "2025. 03. 06",
                                    "shop_addr": "경기 수원시 권선구 평동로79번길 45 (평동, 수원 SK V1 motors)",
                                    "lati": "37.259923",
                                    "longti": "126.992944",
                                    "seize_str": "없음",
                                    "security_str": "없음",
                                    "view_cnt": "115",
                                    "shop_info_arr": {
                                        "shop_name": "카마존",
                                        "shop_addr": "경기 수원시 권선구 평동로79번길 45 (평동, 수원 SK V1 motors) 403호 카마존모터스",
                                        "shop_tell": "031-893-8959",
                                    },
                                    "guild_info_arr": {
                                        "guild_name": "경기도자동차매매사업조합",
                                        "guild_address": "경기도 수원시 팔달구 팔달문로 114번길 25-20",
                                        "guild_tel": "031-242-8940",
                                    },
                                },
                                "lease_info": {},
                                "show_info_desc_area": "1",
                                "options": [
                                    {
                                        "key": "navigation",
                                        "val": "Y",
                                        "kor_name": "내비게이션",
                                    },
                                    {
                                        "key": "black_box",
                                        "val": "Y",
                                        "kor_name": "블랙박스",
                                    },
                                    {
                                        "key": "sunroof",
                                        "val": "Y",
                                        "kor_name": "썬루프",
                                    },
                                    {
                                        "key": "cruise_control",
                                        "val": "Y",
                                        "kor_name": "크루즈컨트롤",
                                    },
                                    {
                                        "key": "back_sensor",
                                        "val": "Y",
                                        "kor_name": "후방감지센서",
                                    },
                                    {
                                        "key": "back_camera",
                                        "val": "Y",
                                        "kor_name": "후방카메라",
                                    },
                                    {
                                        "key": "heat_seat",
                                        "val": "Y",
                                        "kor_name": "열선시트",
                                    },
                                    {
                                        "key": "ventilated_seat",
                                        "val": "Y",
                                        "kor_name": "통풍시트",
                                    },
                                    {
                                        "key": "leather_seat",
                                        "val": "Y",
                                        "kor_name": "가죽시트",
                                    },
                                    {
                                        "key": "auto_aircond",
                                        "val": "Y",
                                        "kor_name": "자동에어컨",
                                    },
                                    {
                                        "key": "electric_trunk",
                                        "val": "Y",
                                        "kor_name": "전동 트렁크",
                                    },
                                    {
                                        "key": "smart_key",
                                        "val": "Y",
                                        "kor_name": "스마트키",
                                    },
                                ],
                                "perform_summary": {
                                    "performance_type": "1",
                                    "perform_url": "",
                                    "change_num": "0",
                                    "metal_num": "2",
                                    "corrosion_num": "0",
                                    "uneven_num": "0",
                                    "scratch_num": "0",
                                    "damage_num": "0",
                                    "accident_history": "무사고",
                                    "coordinate": [
                                        {
                                            "position": "3-4",
                                            "name": "조수석 리어 도어",
                                            "value": "1003|",
                                        },
                                        {
                                            "position": "6-2",
                                            "name": "조수석 쿼터패널",
                                            "value": "1003|",
                                        },
                                    ],
                                    "rent_history": "없음",
                                    "buisiness_history": "없음",
                                    "main_state_history": "양호",
                                    "dashboard_state_history": "양호",
                                    "tuning_history": "있음",
                                },
                                "carhistory_summary": {
                                    "mycar_accident_num": "1회",
                                    "other_accident_num": "없음",
                                    "total_loss_num": "없음",
                                    "flooded_num": "없음",
                                    "number_plate_change_num": "없음",
                                    "owner_change_num": "있음",
                                },
                                "as_info": {
                                    "period_general": "36",
                                    "mileage_general": "60000",
                                    "period_special": "60",
                                    "mileage_special": "100000",
                                    "period_hybrid": "",
                                    "mileage_hybrid": "",
                                    "period_electronic": "",
                                    "mileage_electronic": "",
                                    "as_info_text": "",
                                    "as_info_km": "",
                                    "as_info_month": "",
                                    "as_url_link": "",
                                    "korea_suport": "1",
                                    "cpo_info_text": "",
                                    "cpo_mileage": "",
                                    "cpo_period": "",
                                },
                                "infor_desc": "☆이종호 부장의 이벤트☆\r\n       놓치지 마세요 !!\r\n\r\n2025년 이벤트 ☆\r\n\r\n기대하셔도 좋습니다 ☆\r\n\r\n☆이종호 부장의 소개글 ☆\r\n\r\n12년동안의 영업하면서 \r\n\r\n고객님 한분한분 원하시는 차량을 \r\n\r\n맞춰서 선보인 노하우  기대하셔도 좋습니다!!\r\n\r\n첫차에서는 100% 확인된 차량을 광고 중이며 \r\n\r\n꼼꼼히 심사후 차량을 판매 중 입니다 .\r\n\r\n고객 니즈에 맞춰서 후회 없는 중고차 구매의 힘쓰겠습니다 .  \r\n\r\n◇문의안내 \r\n\r\n24시 상담이 가능하오니 편하게 연락 주시길 바랍니다 .\r\n\r\n통화가 혹시나 어려울때는 문자를 남겨 주시면 빠른 답변 드리겠습니다 .\r\n방문전 연락을 부탁 드립니다 .\r\n\r\n☆고객이 자주하는 질문☆\r\n\r\n1 .할부? 현금? 둘 다 가능한가요?\r\n가능합니다. 은행 중고차할부 프로그램을 통하여 저금리로 적용받으실 수 있습니다.\r\n\r\n2. 비대면 구매 가능한가요?\r\n매장 방문이 힘드시거나 바쁘신 고객님들 \r\n직접 차량상태 확인, 정비 정검 및 보험가입까지 완벽히\r\n안전하게 차량인도를 도와드리겠습니다 \r\n\r\n3.차량 출고 후 결함발견시 사후처리는요?\r\n매입 된 모든 차량은 보험사에 보증보험을 가입하고 출고 합니다. 결함/하자 발생시 가까운 제휴정비소에 입고하여 보증 받으시면 됩니다.\r\n(30일 또는 2,000km 내, 보험사 보증범위 대상)\r\n\r\n4. 타던 차량 처리가능한가요?\r\n가능합니다. 자동차진단 평가사가 정확한 고객님의 차량상태를 확인 후 매입합니다.소유중이신 차량의 단가를 최고가로 매입을 약속 드리겠습니다 \r\n\r\n5. 차구입 시 시간이 얼마나 걸리나요?\r\n현금구입시 약1시간 할부구입시 약 2시간 소요\r\n\r\n◇탁송거래\r\n매장 방문이 힘드시거나 바쁘신 고객님들 \r\n직접 차량상태 확인, 정비 정검 및 보험가입까지 완벽히\r\n안전하게 차량인도를 도와드리겠습니다 \r\n\r\n◇차량매입 , 대차가능\r\n \r\n소유중이신 차량의 단가를 최고가로 매입을 약속 드리겠습니다 \r\n\r\n◇오시는길\r\n→ 주소 : 수원시 권선구",
                                "info_tab": [
                                    {
                                        "tab_id": "0",
                                        "tab_idx": "0",
                                        "title": "총 구매비용은 얼마나 되나요?",
                                        "web_url": "https://web.chutcha.net/cc_webview/buyCalc?keys=bGR6S0JaZ1VHbWNSSTR2aWI2VGVDQT09",
                                        "web_title": "구매비용 계산기",
                                        "web_more_txt": "실제 구매비용을 확인하세요",
                                        "web_icon_img": "/images/chutcha/pc/car_before_check_total_cost.png",
                                    },
                                    {
                                        "tab_id": "1",
                                        "tab_idx": "1",
                                        "title": "내 보험료는 얼마인가요?",
                                        "web_title": "내 보험료 알아보기",
                                        "web_url": "https://www.banksalad.com/car-insurance/prequalification?external-channel=chutcha",
                                        "web_more_txt": "다이렉트로 3초만에",
                                        "web_icon_img": "/files/chutchaApp/popup/202306/e7b8d413c6504d613153a2066510a8fa.png",
                                    },
                                    {
                                        "tab_id": "2",
                                        "tab_idx": "2",
                                        "title": "내 할부한도는 얼마인가요?",
                                        "web_title": "내 할부한도 알아보기",
                                        "web_url": "https://web.chutcha.net/cc_webview/loan/installment?type=1&utm_source=loan_01&keys=bGR6S0JaZ1VHbWNSSTR2aWI2VGVDQT09",
                                        "web_more_txt": "내 금리와 대출 가능 한도는?",
                                        "web_icon_img": "/files/chutchaApp/popup/202306/a4995ed62bfbf40ddb8959a420a20e35.png",
                                    },
                                    {
                                        "tab_id": "4",
                                        "tab_idx": "4",
                                        "title": "혹시 판매하실 차가 있나요?",
                                        "web_title": "내차팔기",
                                        "web_url": "https://sell.chutcha.net/main/main",
                                        "web_more_txt": "비교견적 20개 받아보세요",
                                        "web_icon_img": "/files/chutchaApp/popup/202306/f7b189860e6d1cb7bcd74992bfe9b428.png",
                                    },
                                    {
                                        "tab_id": "7",
                                        "tab_idx": "3",
                                        "title": "이달의 구매혜택은 뭔가요?",
                                        "web_title": "첫차 거래 혜택",
                                        "web_url": "https://static.chutcha.net/event/regular/transactionBenefit/v1/2502",
                                        "web_more_txt": "매달 스페셜한 선물",
                                        "web_icon_img": "/files/chutchaApp/popup/202307/c858c9f9f1aa263e01815fbe1b4b6010.png",
                                    },
                                ],
                                "price_info": {
                                    "model_trim_name": "기아 스팅어 마이스터 3.3 터보 GT 아크로에디션",
                                    "price": "3,450만원 / 월 62만원",
                                    "low_price": "3567",
                                    "high_price": "4826",
                                    "int_price": "3450",
                                },
                                "lease_installment_info": {
                                    "installment": {
                                        "total_month": "48",
                                        "month_price": "62",
                                    },
                                    "lease": [],
                                },
                                "calc_summary_info": {
                                    "car_price": "3,450만원",
                                    "move_reg_price": "254만원",
                                    "commission_price": "40만원",
                                    "total_buy_price": "3,744만원",
                                    "ew_price": "",
                                },
                                "another_sale_keys": "",
                            },
                            "dataUpdateCount": 1,
                            "dataUpdatedAt": 1741432383000,
                            "error": None,
                            "errorUpdateCount": 0,
                            "errorUpdatedAt": 0,
                            "fetchFailureCount": 0,
                            "fetchFailureReason": None,
                            "fetchMeta": None,
                            "isInvalidated": False,
                            "status": "success",
                            "fetchStatus": "idle",
                        },
                        "queryKey": ["carDetailData"],
                        "queryHash": '["carDetailData"]',
                    }
                ],
            },
            "_sentryTraceData": "167a9f0146454736abcd68713a072b1a-22a55b4da0582a41-1",
            "_sentryBaggage": "sentry-environment=production,sentry-release=zBajHN9s8J_C-91YSJB48,sentry-public_key=f659f8b84eee79773e21a88b3062a7a4,sentry-trace_id=167a9f0146454736abcd68713a072b1a,sentry-sample_rate=1,sentry-transaction=%2Fbmc%2Fdetail%2F%5Bkeys%5D,sentry-sampled=true",
        },
        "__N_SSP": True,
    },
    "page": "/bmc/detail/[keys]",
    "query": {"keys": "bGR6S0JaZ1VHbWNSSTR2aWI2VGVDQT09"},
    "buildId": "zBajHN9s8J_C-91YSJB48",
    "isFallback": False,
    "isExperimentalCompile": False,
    "gssp": True,
    "scriptLoader": [],
}
